// GENERATED by scripts/build_dawnhold_map.mjs; do not edit by hand.
// Re-bake with `npm run assets:dawnholdmap` after any Dawnhold layout or
// plan-palette change (tests/dawnhold_map_baked.test.ts guards freshness).
// Plates live in public/map_bg/dawnhold_<story>.webp.

export const BAKED_DAWNHOLD_MAP = {
  fingerprint: '2e39772f',
  plateWidth: 544,
  plateHeight: 576,
  stories: ["ground","solar"],
} as const;
