// GENERATED by scripts/build_map_backgrounds.mjs; do not edit by hand.
// Re-bake with `npm run assets:mapbg` after any world-generation change
// (tests/map_bg_baked.test.ts guards freshness). Plates live in public/map_bg/.

export const BAKED_MAP_BG = {
  seed: 20061,
  pxPerYd: 1.3333333333333333,
  hashRows: 16,
  zones: {
  "eastbrook_vale": {
    "w": 480,
    "h": 480,
    "rowHash": "02700d07"
  },
  "mirefen_marsh": {
    "w": 480,
    "h": 480,
    "rowHash": "01b48fa8"
  },
  "thornpeak_heights": {
    "w": 480,
    "h": 480,
    "rowHash": "4b6ba10a"
  },
  "veiled_hollow": {
    "w": 720,
    "h": 720,
    "rowHash": "85ef5cab"
  },
  "drakelands": {
    "w": 800,
    "h": 800,
    "rowHash": "0575acea"
  },
  "frostveil": {
    "w": 693,
    "h": 693,
    "rowHash": "8e6c60ee"
  },
  "amberfall": {
    "w": 747,
    "h": 747,
    "rowHash": "20a873fd"
  },
  "willowfen": {
    "w": 693,
    "h": 693,
    "rowHash": "44713879"
  },
  "nightbloom": {
    "w": 747,
    "h": 747,
    "rowHash": "eaf735b8"
  },
  "wraithwood": {
    "w": 747,
    "h": 747,
    "rowHash": "1e8a6275"
  },
  "palmreach": {
    "w": 747,
    "h": 747,
    "rowHash": "4837b092"
  },
  "evergarden": {
    "w": 747,
    "h": 747,
    "rowHash": "0a87eedc"
  },
  "galecrest": {
    "w": 693,
    "h": 693,
    "rowHash": "589bfa4c"
  },
  "farshore_isle": {
    "w": 480,
    "h": 480,
    "rowHash": "118be894"
  },
  "world_strip": {
    "w": 140,
    "h": 337,
    "rowHash": "fd1270a8"
  }
},
} as const;
