// GENERATED by scripts/build_map_backgrounds.mjs; do not edit by hand.
// Re-bake with `npm run assets:mapbg` after any world-generation change
// (tests/map_bg_baked.test.ts guards freshness). Plates live in public/map_bg/.

export const BAKED_MAP_BG = {
  seed: 20061,
  plateWidth: 480,
  hashRows: 16,
  zones: {
  "eastbrook_vale": {
    "w": 480,
    "h": 480,
    "rowHash": "02700d07"
  },
  "mirefen_marsh": {
    "w": 480,
    "h": 480,
    "rowHash": "01b48fa8"
  },
  "thornpeak_heights": {
    "w": 480,
    "h": 480,
    "rowHash": "4b6ba10a"
  },
  "veiled_hollow": {
    "w": 480,
    "h": 720,
    "rowHash": "ef330f2b"
  },
  "drakelands": {
    "w": 480,
    "h": 800,
    "rowHash": "8d097343"
  },
  "frostveil": {
    "w": 480,
    "h": 693,
    "rowHash": "3757462c"
  },
  "amberfall": {
    "w": 480,
    "h": 747,
    "rowHash": "2a2652da"
  },
  "willowfen": {
    "w": 480,
    "h": 693,
    "rowHash": "2a925738"
  },
  "nightbloom": {
    "w": 480,
    "h": 747,
    "rowHash": "82acc7eb"
  },
  "wraithwood": {
    "w": 480,
    "h": 747,
    "rowHash": "d3ccbf3d"
  },
  "palmreach": {
    "w": 480,
    "h": 747,
    "rowHash": "defc6d0b"
  },
  "evergarden": {
    "w": 480,
    "h": 747,
    "rowHash": "c77eda50"
  },
  "galecrest": {
    "w": 480,
    "h": 693,
    "rowHash": "1028f11c"
  },
  "farshore_isle": {
    "w": 480,
    "h": 480,
    "rowHash": "118be894"
  },
  "world_strip": {
    "w": 140,
    "h": 337,
    "rowHash": "fd1270a8"
  }
},
} as const;
