// GENERATED by scripts/build_map_backgrounds.mjs; do not edit by hand.
// Re-bake with `npm run assets:mapbg` after any world-generation change
// (tests/map_bg_baked.test.ts guards freshness). Plates live in public/map_bg/.

export const BAKED_MAP_BG = {
  seed: 20061,
  pxPerYd: 1.3333333333333333,
  hashRows: 16,
  zones: {
  "eastbrook_vale": {
    "w": 480,
    "h": 480,
    "rowHash": "23052a47"
  },
  "mirefen_marsh": {
    "w": 480,
    "h": 480,
    "rowHash": "01b48fa8"
  },
  "thornpeak_heights": {
    "w": 480,
    "h": 480,
    "rowHash": "4b6ba10a"
  },
  "veiled_hollow": {
    "w": 720,
    "h": 720,
    "rowHash": "a3819b33"
  },
  "drakelands": {
    "w": 800,
    "h": 800,
    "rowHash": "a3327759"
  },
  "frostveil": {
    "w": 693,
    "h": 693,
    "rowHash": "ef9c68cd"
  },
  "amberfall": {
    "w": 747,
    "h": 747,
    "rowHash": "d8e417de"
  },
  "willowfen": {
    "w": 693,
    "h": 693,
    "rowHash": "5254c288"
  },
  "nightbloom": {
    "w": 747,
    "h": 747,
    "rowHash": "1ce82569"
  },
  "wraithwood": {
    "w": 747,
    "h": 747,
    "rowHash": "57558a1d"
  },
  "palmreach": {
    "w": 747,
    "h": 747,
    "rowHash": "f829b2da"
  },
  "evergarden": {
    "w": 747,
    "h": 747,
    "rowHash": "d8de383d"
  },
  "galecrest": {
    "w": 693,
    "h": 693,
    "rowHash": "95679f7d"
  },
  "farshore_isle": {
    "w": 480,
    "h": 480,
    "rowHash": "f61d149d"
  },
  "world_strip": {
    "w": 140,
    "h": 337,
    "rowHash": "e4577309"
  }
},
} as const;
