import type { AbilityVfxFullSpec } from './ability_vfx_core';

// Reviewed Warrior base records, scoped independently of every other class.
export const WARRIOR_BASE_PROFILES: Readonly<Record<string, AbilityVfxFullSpec>> = {
  heroic_strike: {
    archetype: 'strike',
    palette: 'physical',
    power: 1,
    strike: {
      swings: 1,
      arc: 'horizontal',
    },
    decal: 'scorch',
    buff: {
      orbit: 'weaponGlow',
      o: {
        rate: 1.4,
        size: 0.3,
        radius: 0.5,
      },
    },
    impact: {
      trail: 'sweep',
      sparks: 24,
      light: 0.6,
      flipbook: false,
    },
    accent: '#e4efff',
    filler: true,
  },
  slam: {
    archetype: 'strike',
    palette: 'physical',
    power: 1.1,
    strike: {
      swings: 1,
      arc: 'vertical',
      groundSlam: true,
    },
    windup: 1.5,
    windupStyle: 'weapon',
    motifs: ['fissure'],
    decal: 'crack',
    impact: {
      trail: 'overhead',
      debris: true,
      smoke: true,
      light: 0.7,
    },
    accent: '#e4efff',
    filler: false,
  },
  mortal_strike: {
    archetype: 'strike',
    palette: 'physical',
    power: 1.3,
    strike: {
      swings: 1,
      arc: 'vertical',
      bleed: true,
    },
    windup: 0.4,
    windupStyle: 'weapon',
    motifs: ['crescents'],
    motifAt: 'target',
    linger: 1.5,
    rim: '#e5e9f0',
    impact: {
      flipbook: false,
      ring: false,
      vRing: true,
      sparks: 40,
      debris: true,
      smoke: false,
      trail: 'overhead',
      blood: true,
      light: 0.8,
    },
    accent: '#e5e9f0',
    filler: false,
  },
  execute: {
    archetype: 'strike',
    palette: 'blood',
    power: 1.6,
    finisher: true,
    strike: {
      swings: 1,
      arc: 'vertical',
      groundSlam: true,
    },
    windup: 0.5,
    windupStyle: 'stance',
    impact: {
      flipbook: true,
      ring: true,
      vRing: true,
      sparks: 60,
      debris: true,
      smoke: true,
      trail: 'overhead',
      blood: true,
      light: 0.8,
    },
    accent: '#ff9986',
    filler: false,
  },
  breachmaker: {
    archetype: 'strike',
    palette: 'physical',
    power: 1.25,
    strike: {
      swings: 1,
      arc: 'thrust',
    },
    windup: 0.35,
    windupStyle: 'weapon',
    decal: 'crack',
    linger: 2.5,
    rim: '#e0a05a',
    impact: {
      flipbook: false,
      ring: 1.3,
      vRing: true,
      sparks: 30,
      debris: true,
      smoke: false,
      trail: 'arc',
      blood: false,
      light: 0.9,
    },
    accent: '#e0a05a',
    filler: false,
  },
  overpower: {
    archetype: 'strike',
    palette: 'blood',
    power: 1,
    strike: {
      swings: 1,
      arc: 'uppercut',
    },
    impact: {
      flipbook: false,
      ring: false,
      vRing: true,
      sparks: 22,
      smoke: false,
      trail: 'riposte',
      light: 0.6,
    },
    accent: '#ff9986',
    filler: true,
  },
  victory_rush: {
    archetype: 'strike',
    palette: 'physical',
    power: 1.15,
    strike: {
      swings: 1,
      arc: 'uppercut',
    },
    windupStyle: 'none',
    motifs: ['fountain'],
    motifAt: 'caster',
    accent: '#b8e6c8',
    linger: 1.5,
    rim: '#dfe8dd',
    impact: {
      trail: 'riposte',
      ring: false,
      vRing: false,
      sparks: 18,
      flipbook: false,
      debris: false,
      smoke: false,
      light: 1.4,
    },
    filler: false,
  },
  raging_gale: {
    archetype: 'strike',
    palette: 'physical',
    power: 1.1,
    strike: {
      swings: 2,
      arc: 'horizontal',
    },
    windupStyle: 'none',
    hot: 0.15,
    rim: '#dfe9f4',
    linger: 1,
    impact: {
      trail: 'x',
      flipbook: false,
      ring: false,
      vRing: false,
      sparks: 30,
      debris: false,
      smoke: false,
      light: 0.6,
    },
    accent: '#dfe9f4',
    filler: false,
  },
  red_harvest: {
    archetype: 'strike',
    palette: 'blood',
    power: 1.25,
    strike: {
      swings: 3,
      arc: 'horizontal',
      bleed: true,
    },
    windupStyle: 'none',
    rim: '#d41f2e',
    linger: 2.5,
    impact: {
      flipbook: false,
      ring: false,
      vRing: false,
      sparks: 26,
      debris: false,
      smoke: false,
      trail: 'low',
      blood: true,
      light: 0.7,
    },
    accent: '#d41f2e',
    filler: false,
  },
  bloodthirst: {
    archetype: 'strike',
    palette: 'blood',
    power: 1.2,
    strike: {
      swings: 2,
      arc: 'claws',
      bleed: true,
    },
    windupStyle: 'none',
    motifs: ['fountain'],
    motifAt: 'target',
    linger: 1,
    rim: '#c41022',
    impact: {
      flipbook: false,
      ring: 1.4,
      vRing: true,
      sparks: 34,
      debris: true,
      smoke: false,
      trail: 'x',
      blood: true,
      light: 0.6,
    },
    accent: '#c41022',
    filler: false,
  },
  cleave: {
    archetype: 'nova',
    palette: 'physical',
    power: 0.95,
    nova: {
      radius: 5,
    },
    strike: {
      swings: 1,
      arc: 'sweep',
    },
    windupStyle: 'none',
    motifs: ['bladestorm'],
    impact: {
      trail: 'sweep',
      sparks: 24,
      flipbook: false,
      ring: false,
      light: 0.6,
    },
    accent: '#e4efff',
    filler: false,
  },
  revenge: {
    archetype: 'strike',
    palette: 'physical',
    power: 1.05,
    strike: {
      swings: 1,
      arc: 'horizontal',
    },
    windupStyle: 'none',
    linger: 1,
    rim: '#b8cbe0',
    impact: {
      trail: 'sweep',
      ring: 1.4,
      vRing: true,
      sparks: 26,
      flipbook: false,
      debris: false,
      smoke: false,
      light: 0.9,
    },
    accent: '#b8cbe0',
    filler: false,
  },
  hamstring: {
    archetype: 'strike',
    palette: 'blood',
    power: 0.7,
    strike: {
      swings: 1,
      arc: 'low',
      bleed: true,
    },
    debuff: {
      orbit: 'speedlines',
      o: {
        n: 3,
        rate: 1.5,
        size: 0.2,
        radius: 1.15,
      },
    },
    impact: {
      flipbook: false,
      ring: false,
      sparks: 8,
      trail: 'low',
      blood: true,
      light: 0.5,
    },
    accent: '#ff9986',
    filler: true,
  },
  pummel: {
    archetype: 'strike',
    palette: 'physical',
    power: 0.7,
    strike: {
      swings: 1,
      arc: 'uppercut',
    },
    windupStyle: 'none',
    cc: {
      style: 'stars',
    },
    linger: 4.2,
    impact: {
      trail: 'x',
      flipbook: false,
      ring: false,
      vRing: true,
      sparks: 10,
      debris: false,
      smoke: false,
      light: 0.5,
    },
    accent: '#e4efff',
    filler: true,
  },
  sunder_armor: {
    archetype: 'strike',
    palette: 'physical',
    power: 0.8,
    strike: {
      swings: 1,
      arc: 'uppercut',
    },
    impact: {
      flipbook: false,
      ring: false,
      sparks: 45,
      debris: true,
      smoke: false,
      light: 0.6,
    },
    decal: 'crack',
    accent: '#e4efff',
    filler: false,
  },
  whirlwind: {
    archetype: 'nova',
    palette: 'physical',
    power: 1.2,
    nova: {
      radius: 8,
    },
    strike: {
      swings: 2,
      arc: 'horizontal',
    },
    windup: 0.3,
    windupStyle: 'vortex',
    motifs: ['bladestorm'],
    linger: 1.5,
    rim: '#dbe6f4',
    impact: {
      flipbook: false,
      ring: 1.6,
      vRing: false,
      sparks: 34,
      debris: true,
      smoke: false,
      trail: 'sweep',
      blood: true,
      light: 0.7,
    },
    accent: '#dbe6f4',
    filler: false,
  },
  bladestorm: {
    archetype: 'nova',
    palette: 'physical',
    power: 1.5,
    nova: {
      radius: 6,
    },
    windup: 0.5,
    windupStyle: 'vortex',
    motifs: ['bladestorm'],
    motifEvery: 0.45,
    motifR: 4.2,
    spin: {
      rate: 1.7,
      clip: '1H_Melee_Attack_Slice_Diagonal',
      timeScale: 1.15,
    },
    hot: 0.3,
    linger: 4,
    rim: '#eef2f8',
    buff: {
      style: 'raise',
      orbit: 'sparks',
      shellDur: 2,
      o: {
        n: 4,
        size: 0.7,
        tex: 'chip',
        rate: 4.5,
        weave: 0.12,
        radius: 3.4,
        incline: 0.05,
        tickEvery: 0.9,
      },
    },
    impact: {
      trail: 'sweep',
      ring: 2.2,
      vRing: true,
      sparks: 44,
      debris: true,
      smoke: false,
      flipbook: false,
      light: 1,
    },
    accent: '#eef2f8',
    filler: false,
  },
  thunder_clap: {
    archetype: 'nova',
    palette: 'storm',
    power: 1,
    nova: {
      radius: 8,
    },
    windup: 0.3,
    windupStyle: 'vortex',
    motifs: ['pillars'],
    decal: 'crack',
    impact: {
      ring: 1.3,
      debris: true,
      smoke: true,
      light: 0.6,
    },
    accent: '#edeeff',
    filler: false,
  },
  faultline: {
    archetype: 'nova',
    palette: 'physical',
    power: 1.2,
    nova: {
      radius: 8,
    },
    windup: 0.35,
    windupStyle: 'stance',
    motifs: ['fissure'],
    motifAt: 'caster',
    decal: 'crack',
    linger: 1.8,
    rim: '#c8b89a',
    impact: {
      flipbook: false,
      ring: 2,
      vRing: false,
      sparks: 14,
      debris: true,
      smoke: true,
      light: 0.8,
    },
    accent: '#c8b89a',
    filler: false,
  },
  charge: {
    archetype: 'dash',
    palette: 'physical',
    power: 1.35,
    spirit: null,
    impact: {
      ring: 1.8,
      sparks: 34,
      debris: true,
      smoke: true,
      light: 1.5,
      flipbook: false,
      vRing: true,
      trail: 'sweep',
    },
    tint: '#dfe9f4',
    accent: '#f2f7ff',
    hot: 0.25,
    rim: '#e5231b',
    windup: 0.2,
    windupStyle: 'stance',
    buff: {
      style: 'raise',
      orbit: 'speedlines',
      shellDur: 1.1,
      o: {
        rate: 2,
      },
    },
    debuff: {
      orbit: 'runes',
      o: {
        n: 4,
        size: 0.24,
        tex: 'chip',
        rate: 0.7,
        weave: 0.03,
        radius: 0.85,
        incline: 0,
      },
    },
    motifs: ['fissure'],
    motifAt: 'target',
    decal: 'crack',
    linger: 1.2,
    filler: false,
  },
  heroic_leap: {
    archetype: 'dash',
    palette: 'physical',
    power: 1.25,
    spirit: null,
    windup: 0.3,
    windupStyle: 'stance',
    decal: 'crack',
    linger: 1.2,
    rim: '#dfe8f2',
    impact: {
      ring: 2.2,
      vRing: false,
      sparks: 20,
      debris: true,
      smoke: true,
      flipbook: false,
      trail: 'overhead',
      light: 1,
    },
    accent: '#dfe8f2',
    filler: false,
  },
  shield_slam: {
    archetype: 'strike',
    palette: 'physical',
    power: 1.2,
    strike: {
      swings: 1,
      arc: 'thrust',
    },
    windup: 0.3,
    windupStyle: 'stance',
    motifs: ['gavel'],
    motifAt: 'target',
    decal: 'crack',
    linger: 1,
    rim: '#bcd0e8',
    impact: {
      flipbook: false,
      ring: 1.6,
      vRing: true,
      sparks: 16,
      debris: true,
      smoke: true,
      blood: false,
      light: 1.4,
    },
    accent: '#bcd0e8',
    filler: false,
  },
  raised_guard: {
    archetype: 'buff',
    palette: 'physical',
    power: 0.75,
    buff: {
      style: 'raise',
      orbit: 'none',
      shellDur: 2.5,
      o: {
        tickEvery: 2.2,
      },
    },
    windup: 0.3,
    windupStyle: 'stance',
    linger: 4,
    rim: '#9fb9d4',
    impact: {
      flipbook: false,
      ring: false,
      vRing: 1.4,
      sparks: 8,
      debris: false,
      smoke: false,
      light: 1.1,
      liteAudio: true,
    },
    accent: '#9fb9d4',
    filler: false,
  },
  iron_resolve: {
    archetype: 'buff',
    palette: 'physical',
    power: 0.95,
    barrier: true,
    buff: {
      style: 'raise',
      orbit: 'halo',
      shellDur: 2.5,
      o: {
        n: 5,
        size: 0.34,
        tex: 'chip',
        rate: 0.6,
        weave: 0.04,
        radius: 0.55,
        incline: 0,
        tickEvery: 2.4,
      },
    },
    motifs: ['chains'],
    motifAt: 'caster',
    windup: 0.4,
    windupStyle: 'stance',
    linger: 4,
    rim: '#8b97a6',
    decal: 'crack',
    impact: {
      flipbook: false,
      ring: 1.2,
      vRing: false,
      sparks: 14,
      debris: true,
      smoke: false,
      light: 1.2,
    },
    accent: '#8b97a6',
    filler: false,
  },
  defensive_stance: {
    archetype: 'buff',
    palette: 'physical',
    power: 0.5,
    buff: {
      style: 'raise',
      shellDur: 2,
      orbit: 'plates',
      o: {
        n: 3,
        size: 1.3,
        rate: 0.8,
        tickEvery: 5,
      },
    },
    linger: 2,
    windup: 0.4,
    windupStyle: 'stance',
    motifs: ['barrier'],
    rim: '#8fa8bd',
    impact: {
      light: 0.5,
    },
    accent: '#8fa8bd',
    filler: false,
  },
  die_by_sword: {
    archetype: 'buff',
    palette: 'physical',
    power: 0.95,
    buff: {
      style: 'raise',
      orbit: 'speedlines',
      shellDur: 2.5,
      o: {
        rate: 3,
        tickEvery: 1.3,
      },
    },
    windup: 0.3,
    windupStyle: 'weapon',
    linger: 4,
    rim: '#d4dde8',
    impact: {
      vRing: 1.5,
      ring: false,
      sparks: 16,
      flipbook: false,
      debris: false,
      smoke: false,
      light: 1,
      liteAudio: true,
    },
    accent: '#d4dde8',
    filler: false,
  },
  battle_shout: {
    archetype: 'shout',
    palette: 'blood',
    power: 1.05,
    shout: {
      radius: 6,
    },
    buff: {
      style: 'raise',
      orbit: 'weaponGlow',
      shellDur: 1.5,
      o: {
        rate: 1.8,
        tickEvery: 4,
      },
    },
    linger: 3,
    windupStyle: 'none',
    rim: '#ff4636',
    impact: {
      ring: 2,
      vRing: true,
      light: 3.2,
    },
    accent: '#ff4636',
    filler: false,
  },
  rallying_cry: {
    archetype: 'shout',
    palette: 'physical',
    power: 1.15,
    shout: {
      radius: 9,
    },
    buff: {
      style: 'raise',
      orbit: 'wings',
      shellDur: 2,
      o: {
        ribs: 5,
        span: 1.1,
        flapRate: 0.9,
        tickEvery: 3.2,
      },
    },
    windupStyle: 'none',
    linger: 4,
    rim: '#e8eef5',
    impact: {
      ring: 2.6,
      vRing: true,
      sparks: 0,
      flipbook: false,
      debris: false,
      smoke: false,
      light: 2.6,
    },
    accent: '#e8eef5',
    filler: false,
  },
  emboldening_roar: {
    archetype: 'shout',
    palette: 'blood',
    power: 1.1,
    shout: {
      radius: 9,
    },
    buff: {
      style: 'raise',
      orbit: 'halo',
      shellDur: 2,
      o: {
        n: 3,
        size: 0.3,
        tex: 'star',
        rate: 2.2,
        weave: 0.1,
        radius: 0.6,
        incline: 0.12,
        tickEvery: 1.5,
      },
    },
    windupStyle: 'none',
    linger: 4,
    rim: '#ff5a3c',
    impact: {
      ring: 2.2,
      vRing: false,
      sparks: 18,
      flipbook: false,
      debris: false,
      smoke: false,
      light: 2.2,
    },
    accent: '#ff5a3c',
    filler: false,
  },
  defiant_bellow: {
    archetype: 'shout',
    palette: 'physical',
    power: 1.1,
    shout: {
      radius: 10,
      target: true,
    },
    windup: 0.3,
    windupStyle: 'stance',
    linger: 2,
    rim: '#c9d6e4',
    impact: {
      ring: 2.8,
      vRing: true,
      sparks: 6,
      flipbook: false,
      debris: false,
      smoke: false,
      light: 2,
    },
    accent: '#c9d6e4',
    filler: false,
  },
  demoralizing_shout: {
    archetype: 'shout',
    palette: 'shadow',
    power: 1.15,
    shout: {
      radius: 10,
      target: true,
    },
    motifs: ['swarm'],
    motifAt: 'caster',
    windup: 0.3,
    windupStyle: 'stance',
    linger: 2,
    rim: '#6b5a8c',
    impact: {
      ring: 2.6,
      vRing: false,
      sparks: 0,
      smoke: true,
      flipbook: false,
      debris: false,
      light: 2,
    },
    accent: '#6b5a8c',
    filler: false,
  },
  intimidating_shout: {
    archetype: 'shout',
    palette: 'shadow',
    power: 1.2,
    shout: {
      radius: 8,
      target: true,
    },
    motifs: ['implosion'],
    windup: 0.3,
    windupStyle: 'stance',
    linger: 2.5,
    rim: '#8a6ab8',
    debuff: {
      orbit: 'halo',
      o: {
        n: 3,
        size: 0.3,
        tex: 'glow',
        rate: 0.5,
        weave: 0.12,
        radius: 0.5,
        incline: 0.06,
      },
    },
    impact: {
      ring: 2.4,
      vRing: false,
      sparks: 0,
      flipbook: false,
      debris: false,
      smoke: true,
      light: 1.8,
    },
    accent: '#8a6ab8',
    filler: false,
  },
  taunt: {
    archetype: 'shout',
    palette: 'physical',
    power: 0.85,
    shout: {
      radius: 3,
      target: true,
    },
    motifs: ['claws'],
    impact: {
      ring: 1.8,
      vRing: true,
      sparks: 10,
      light: 2.6,
    },
    motifAt: 'target',
    accent: '#e4efff',
    filler: false,
  },
  piercing_howl: {
    archetype: 'shout',
    palette: 'physical',
    power: 1.1,
    shout: {
      radius: 12,
    },
    windupStyle: 'none',
    linger: 2,
    rim: '#9fb4c8',
    impact: {
      ring: 3,
      vRing: false,
      sparks: 0,
      flipbook: false,
      debris: false,
      smoke: true,
      light: 1.6,
    },
    accent: '#9fb4c8',
    filler: false,
  },
  bloodrage: {
    archetype: 'buff',
    palette: 'blood',
    power: 0.7,
    buff: {
      style: 'raise',
      shellDur: 1.5,
      orbit: 'heartbeat',
      o: {
        bpm: 96,
        ringR: 1,
        tickEvery: 2.8,
      },
    },
    linger: 2,
    windupStyle: 'none',
    rim: '#9e1622',
    impact: {
      blood: true,
      light: 1.3,
    },
    accent: '#9e1622',
    filler: false,
  },
  berserker_rage: {
    archetype: 'buff',
    palette: 'blood',
    power: 1.15,
    self: true,
    buff: {
      style: 'raise',
      orbit: 'heartbeat',
      shellDur: 1.5,
      o: {
        bpm: 150,
        ringR: 2.4,
        tickEvery: 0.6,
      },
    },
    motifs: ['claws'],
    motifAt: 'caster',
    linger: 3.5,
    windup: 0.3,
    windupStyle: 'stance',
    rim: '#ff2a14',
    impact: {
      flipbook: false,
      ring: 1.8,
      vRing: true,
      sparks: 20,
      debris: false,
      smoke: false,
      blood: true,
      light: 2.6,
    },
    accent: '#ff2a14',
    filler: false,
  },
  recklessness: {
    archetype: 'buff',
    palette: 'blood',
    power: 1.2,
    buff: {
      style: 'raise',
      orbit: 'heartbeat',
      shellDur: 2,
      o: {
        bpm: 170,
        ringR: 3,
        tickEvery: 0.5,
      },
    },
    windup: 0.25,
    windupStyle: 'stance',
    linger: 4,
    rim: '#ff3820',
    impact: {
      sparks: 22,
      ring: false,
      vRing: false,
      flipbook: false,
      debris: false,
      smoke: false,
      light: 1.4,
      liteAudio: true,
    },
    accent: '#ff3820',
    filler: false,
  },
  battle_stance: {
    archetype: 'buff',
    palette: 'physical',
    power: 0.7,
    buff: {
      style: 'raise',
      orbit: 'runes',
      shellDur: 1.8,
      o: {
        n: 5,
        size: 0.4,
        tex: 'chip',
        rate: 0.7,
        weave: 0.02,
        radius: 1.15,
        incline: 0,
        tickEvery: 3.5,
      },
    },
    windup: 0.3,
    windupStyle: 'stance',
    linger: 3.5,
    rim: '#cdd9e6',
    impact: {
      flipbook: false,
      ring: 1.2,
      vRing: false,
      sparks: 10,
      debris: false,
      smoke: false,
      light: 0.9,
      liteAudio: true,
    },
    accent: '#cdd9e6',
    filler: false,
  },
  berserker_stance: {
    archetype: 'buff',
    palette: 'blood',
    power: 0.8,
    buff: {
      style: 'raise',
      orbit: 'sparks',
      shellDur: 1.8,
      o: {
        n: 3,
        size: 0.3,
        tex: 'chip',
        rate: 2.6,
        weave: 0.3,
        radius: 0.8,
        incline: 0.15,
        tickEvery: 1.6,
      },
    },
    windup: 0.25,
    windupStyle: 'stance',
    linger: 3.5,
    rim: '#e03428',
    impact: {
      flipbook: false,
      ring: false,
      vRing: false,
      sparks: 16,
      debris: false,
      smoke: false,
      light: 0.9,
      liteAudio: true,
    },
    accent: '#e03428',
    filler: false,
  },
  avatar: {
    archetype: 'buff',
    palette: 'physical',
    power: 1.5,
    buff: {
      style: 'morph',
      orbit: 'plates',
      shellDur: 3,
      o: {
        n: 6,
        size: 1.5,
        tex: 'chip',
        rate: 0.35,
        weave: 0.02,
        radius: 1.35,
        incline: 0,
        tickEvery: 2,
      },
    },
    windup: 0.5,
    windupStyle: 'stance',
    motifs: ['implosion'],
    decal: 'crack',
    hot: 0.1,
    linger: 4,
    rim: '#d8dce2',
    impact: {
      ring: 1.8,
      vRing: false,
      sparks: 16,
      debris: true,
      smoke: true,
      flipbook: false,
      light: 1.6,
    },
    accent: '#d8dce2',
    filler: false,
  },
  furious_mending: {
    archetype: 'buff',
    palette: 'blood',
    power: 0.7,
    buff: {
      style: 'raise',
      orbit: 'leaves',
      shellDur: 2,
      o: {
        density: 10,
        spread: 0.8,
        up: 1.2,
        tickEvery: 2.6,
      },
    },
    windup: 0.25,
    windupStyle: 'none',
    linger: 4,
    rim: '#d8685c',
    impact: {
      flipbook: false,
      ring: false,
      vRing: false,
      sparks: 0,
      debris: false,
      smoke: false,
      light: 1,
      liteAudio: true,
    },
    accent: '#d8685c',
    filler: false,
  },
  sanguine_aura: {
    archetype: 'buff',
    palette: 'blood',
    power: 1.1,
    buff: {
      style: 'raise',
      orbit: 'weaponGlow',
      weaponAura: '#ff4636',
      shellDur: 2.5,
      o: {
        rate: 0.5,
        tickEvery: 1.6,
      },
    },
    windup: 0.3,
    windupStyle: 'weapon',
    linger: 4,
    rim: '#8e1220',
    impact: {
      ring: 2,
      vRing: false,
      sparks: 12,
      flipbook: false,
      debris: false,
      smoke: false,
      blood: true,
      light: 1.8,
    },
    accent: '#8e1220',
    filler: false,
  },
  sweeping_strikes: {
    archetype: 'buff',
    palette: 'physical',
    power: 0.9,
    buff: {
      style: 'raise',
      orbit: 'sparks',
      shellDur: 2,
      o: {
        n: 2,
        size: 0.9,
        tex: 'rays',
        rate: 1.2,
        weave: 0.06,
        radius: 1.3,
        incline: 0.05,
        tickEvery: 2.8,
      },
    },
    windup: 0.3,
    windupStyle: 'weapon',
    linger: 4,
    rim: '#dbe6f4',
    impact: {
      flipbook: false,
      ring: false,
      vRing: false,
      sparks: 12,
      debris: false,
      smoke: false,
      light: 0.8,
      liteAudio: true,
    },
    accent: '#dbe6f4',
    filler: false,
  },
  storm_bolt: {
    archetype: 'bolt',
    palette: 'physical',
    power: 1.1,
    bolt: {
      speed: 22,
      headScale: 1.1,
      style: 'rock',
      coils: false,
      jagged: false,
      forkEvery: 0,
    },
    windup: 0.3,
    windupStyle: 'weapon',
    linger: 1.5,
    rim: '#cfdae6',
    impact: {
      flipbook: false,
      ring: 1.2,
      vRing: true,
      sparks: 24,
      debris: false,
      smoke: false,
      light: 0.9,
    },
    accent: '#cfdae6',
    filler: false,
  },
  measured_fury: {
    archetype: 'buff',
    palette: 'physical',
    power: 0.55,
    buff: {
      style: 'raise',
      orbit: 'none',
      shellDur: 1.2,
      o: {
        tickEvery: 5,
      },
    },
    windup: 0.2,
    windupStyle: 'none',
    linger: 2.5,
    rim: '#aab8c6',
    impact: {
      flipbook: false,
      ring: false,
      vRing: false,
      sparks: 0,
      debris: false,
      smoke: false,
      light: 0.5,
      liteAudio: true,
    },
    accent: '#aab8c6',
    filler: false,
  },
  seasoned_soldier: {
    archetype: 'buff',
    palette: 'physical',
    power: 0.6,
    buff: {
      style: 'raise',
      orbit: 'none',
      shellDur: 1.3,
      o: {
        tickEvery: 4.2,
      },
    },
    windup: 0.2,
    windupStyle: 'none',
    linger: 2.5,
    rim: '#c2cfdb',
    impact: {
      flipbook: false,
      ring: false,
      vRing: false,
      sparks: 10,
      debris: false,
      smoke: false,
      light: 0.7,
      liteAudio: true,
    },
    accent: '#c2cfdb',
    filler: false,
  },
  sudden_death: {
    archetype: 'buff',
    palette: 'physical',
    power: 0.62,
    buff: {
      style: 'raise',
      orbit: 'none',
      shellDur: 1.4,
      o: {
        tickEvery: 3,
      },
    },
    windup: 0.2,
    windupStyle: 'none',
    hot: 0.2,
    linger: 2.5,
    rim: '#d4dde6',
    impact: {
      flipbook: false,
      ring: false,
      vRing: true,
      sparks: 2,
      debris: false,
      smoke: false,
      light: 0.9,
      liteAudio: true,
    },
    accent: '#d4dde6',
    filler: false,
  },
  diabolical_twinstrike: {
    archetype: 'buff',
    palette: 'blood',
    power: 0.58,
    buff: {
      style: 'raise',
      orbit: 'none',
      shellDur: 1.2,
      o: {
        tickEvery: 1.8,
      },
    },
    windup: 0.2,
    windupStyle: 'none',
    linger: 2.5,
    rim: '#c8322a',
    impact: {
      flipbook: false,
      ring: false,
      vRing: false,
      sparks: 12,
      debris: false,
      smoke: false,
      light: 0.7,
      liteAudio: true,
    },
    accent: '#c8322a',
    filler: false,
  },
  cleaving_blows: {
    archetype: 'buff',
    palette: 'blood',
    power: 0.56,
    buff: {
      style: 'raise',
      orbit: 'none',
      shellDur: 1.2,
      o: {
        tickEvery: 2.4,
      },
    },
    windup: 0.2,
    windupStyle: 'none',
    linger: 2.5,
    rim: '#b03040',
    impact: {
      flipbook: false,
      ring: false,
      vRing: false,
      sparks: 8,
      debris: false,
      smoke: false,
      trail: 'x',
      light: 0.6,
      liteAudio: true,
    },
    accent: '#b03040',
    filler: false,
  },
  deep_wounds: {
    archetype: 'buff',
    palette: 'blood',
    power: 0.55,
    buff: {
      style: 'raise',
      orbit: 'none',
      shellDur: 1.5,
      o: {
        tickEvery: 3.8,
      },
    },
    windup: 0.2,
    windupStyle: 'none',
    linger: 3,
    rim: '#9e1622',
    impact: {
      flipbook: false,
      ring: false,
      vRing: false,
      sparks: 0,
      debris: false,
      smoke: false,
      blood: true,
      light: 0.4,
      liteAudio: true,
    },
    accent: '#9e1622',
    filler: false,
  },
  enrage_passive: {
    archetype: 'buff',
    palette: 'blood',
    power: 0.65,
    buff: {
      style: 'raise',
      orbit: 'none',
      shellDur: 1.2,
      o: {
        tickEvery: 1.2,
      },
    },
    windup: 0.2,
    windupStyle: 'none',
    linger: 2.5,
    rim: '#ff2a14',
    impact: {
      flipbook: false,
      ring: false,
      vRing: false,
      sparks: 14,
      debris: false,
      smoke: false,
      light: 1.1,
      liteAudio: true,
    },
    accent: '#ff2a14',
    filler: false,
  },
};
