// Pure spatial policy for renderer zone streaming. Only resident zones own
// render geometry. Outdoor fog contracts before an unloaded zone can enter the
// visible/culling envelope; crossing the boundary uses the normal loading
// transition to materialize that zone without stealing live gameplay frames.

import { STRIP_MAX_X, STRIP_MIN_X } from '../sim/data';
import type { ZoneDef } from '../sim/types';

export const MAX_OUTDOOR_FOG_FAR = 120;
export const MIN_OUTDOOR_FOG_FAR = 45;
export const UNPREPARED_ZONE_FOG_GUARD = 8;

/** Squared XZ distance from a point to a zone's exact rectangle. */
export function distanceSqToZone(zone: ZoneDef, x: number, z: number): number {
  const minX = zone.xMin ?? STRIP_MIN_X;
  const maxX = zone.xMax ?? STRIP_MAX_X;
  const dx = x < minX ? minX - x : x > maxX ? x - maxX : 0;
  const dz = z < zone.zMin ? zone.zMin - z : z > zone.zMax ? z - zone.zMax : 0;
  return dx * dx + dz * dz;
}

/**
 * Cap outdoor visibility before the closest unloaded zone rectangle. The cap
 * drops immediately as the camera approaches a boundary and may ease back out
 * after the destination becomes resident; the renderer owns that temporal
 * policy. No geometry is generated by this query.
 */
export function fogFarForPreparedZones(
  zones: readonly ZoneDef[],
  preparedZoneIds: ReadonlySet<string>,
  cameraX: number,
  cameraZ: number,
  requestedFar: number,
): number {
  let nearestSq = Number.POSITIVE_INFINITY;
  for (const zone of zones) {
    if (preparedZoneIds.has(zone.id)) continue;
    nearestSq = Math.min(nearestSq, distanceSqToZone(zone, cameraX, cameraZ));
  }
  if (!Number.isFinite(nearestSq)) return Math.min(requestedFar, MAX_OUTDOOR_FOG_FAR);
  const beforeUnprepared = Math.sqrt(nearestSq) - UNPREPARED_ZONE_FOG_GUARD;
  return Math.max(
    MIN_OUTDOOR_FOG_FAR,
    Math.min(requestedFar, MAX_OUTDOOR_FOG_FAR, beforeUnprepared),
  );
}
