import type { AbilityDef } from '../types';

const common: AbilityDef[] = [
  {
    id: 'divine_ascension',
    name: 'Divine Ascension',
    class: 'paladin',
    learnLevel: 1,
    cost: 0,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'divineAscension' }],
    description:
      'Consume 20 Devotion to gain 5 Ascension charges for up to 45 sec. Marked abilities consume one charge and gain an additional effect.',
  },
  {
    id: 'aura_mastery',
    name: 'Aura Mastery',
    class: 'paladin',
    learnLevel: 20,
    cost: 0,
    castTime: 0,
    cooldown: 120,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    offGcd: true,
    effects: [
      {
        type: 'buffTarget',
        kind: 'buff_aura_mastery',
        value: 1,
        duration: 8,
        party: true,
      },
    ],
    description:
      'For 8 sec, empower every active combat aura in your group: Bastion Devotion reduces damage by 15%, and both Requital Aura effects deal 15 Holy damage. Repeated uses refresh instead of stacking.',
  },
  {
    id: 'devotion_ward',
    name: 'Bastion Devotion',
    class: 'paladin',
    learnLevel: 2,
    cost: 30,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    exclusiveGroup: 'paladin_devotion',
    effects: [
      {
        type: 'buffTarget',
        kind: 'buff_dr',
        value: 0.05,
        duration: 0,
        permanent: true,
        party: true,
      },
    ],
    description:
      'Reduce damage taken by you and party members by 5% until death or replacement. Only this aura and Requital Aura replace each other; Radiant, Dawn, and Grace Devotion coexist.',
  },
  {
    id: 'hammer_of_grace',
    name: 'Hammer of Grace',
    class: 'paladin',
    learnLevel: 4,
    cost: 0,
    castTime: 0,
    cooldown: 7,
    range: 20,
    school: 'holy',
    projectile: true,
    requiresTarget: true,
    effects: [
      {
        type: 'directDamage',
        min: 95,
        max: 115,
        restoreMana: 70,
        selfHealDamageFrac: 0.5,
      },
    ],
    description:
      'Instantly hurl a holy hammer at an enemy within 20 m for $d, restoring 70 mana, healing yourself for 50% of damage dealt, and generating 1 Devotion when it deals damage. Solar Reprisal lets Hammer of Grace ignore its cooldown and heal you for 100% of damage dealt.',
  },
  {
    id: 'hushbrand',
    name: 'Hushbrand',
    class: 'paladin',
    specs: ['protection', 'retribution'],
    learnLevel: 4,
    cost: 0,
    castTime: 0,
    cooldown: 15,
    range: 5,
    school: 'physical',
    requiresTarget: true,
    offGcd: true,
    effects: [{ type: 'interrupt', lockout: 4 }],
    description: 'Interrupts spellcasting and prevents spells from that school for 4 sec.',
  },
  {
    id: 'guardian_covenant',
    name: 'Guardian Covenant',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 8,
    cost: 35,
    castTime: 0,
    cooldown: 45,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    offGcd: true,
    effects: [{ type: 'buffTarget', kind: 'buff_dr', value: 0.2, duration: 8 }],
    description: 'Protects an ally, reducing their damage taken by 20% for 8 sec.',
  },
  {
    id: 'solar_step',
    name: 'Solar Step',
    class: 'paladin',
    learnLevel: 5,
    cost: 20,
    castTime: 0,
    cooldown: 30,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_speed', value: 2.5, duration: 2 }],
    description: 'Increase your movement speed by 150% for 2 sec.',
  },
  {
    id: 'solar_invocation',
    name: 'Solar Invocation',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 12,
    cost: 80,
    castTime: 0,
    cooldown: 8,
    range: 30,
    school: 'holy',
    projectile: false,
    requiresTarget: true,
    targetType: 'any',
    effects: [
      { type: 'heal', min: 180, max: 220 },
      { type: 'directDamage', min: 120, max: 150 },
    ],
    description:
      'Instantly heal an ally for $d or deal moderate Holy damage to an enemy. Either use generates 1 Devotion. During Ascension, a healing cast also heals allied players within 10 m of the target for half as much.',
  },
  {
    id: 'recall_the_fallen',
    name: 'Recall the Fallen',
    class: 'paladin',
    // Earned through the Divine Tome quest chain, not trained: hidden until
    // q_rite_of_redemption is turned in (abilitiesKnownAt's requiresQuest gate).
    // No spec lock: any paladin who completes the rite can call back the fallen.
    // learnLevel matches the final quest's minLevel (6): the level gate and the
    // quest gate both apply, so a mismatch would hide the ability past turn-in.
    requiresQuest: 'q_rite_of_redemption',
    learnLevel: 6,
    cost: 60,
    castTime: 8,
    cooldown: 0,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    targetsDead: true,
    partyOnlyTarget: true,
    requiresOutOfCombat: true,
    effects: [{ type: 'resurrectAlly', hpFrac: 0.35 }],
    description: 'Returns a dead group member to life with 35% health and mana.',
  },
  {
    id: 'beacon_of_light',
    name: 'Beacon of Light',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 16,
    cost: 60,
    castTime: 0,
    cooldown: 7,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    partyOnlyTarget: true,
    effects: [{ type: 'beaconOfLight' }],
    description:
      'Mark one group member as your Beacon of Light. 50% of your effective direct healing on another group member within 60 m also heals the Beacon. Area and periodic healing do not transfer. Lasts until either of you dies.',
  },
];

const retribution: AbilityDef[] = [
  // Final Edict is the Retribution weapon strike + Devotion builder from level 1 (it
  // absorbed the old Oathstrike's starter role, removed 2026-07-22 as a duplicate
  // strike). Devotion is spent on Divine Ascension, which empowers marked abilities.
  {
    id: 'final_edict',
    name: 'Final Edict',
    class: 'paladin',
    specs: ['retribution'],
    learnLevel: 1,
    cost: 25,
    castTime: 0,
    cooldown: 8,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'weaponStrike', bonus: 52, weaponMult: 1.4 }],
    description:
      "Deliver a crushing weapon strike and generate 1 Devotion when it deals damage. A successful hit reduces Dawnfall's remaining cooldown by 2 sec. Successful auto-attacks and Final Edict hits have a 15% chance to grant Dawn's Wrath for 8 sec. Ascension also releases a Holy explosion around you.",
  },
  {
    id: 'dawnfall',
    name: 'Dawnfall',
    class: 'paladin',
    specs: ['retribution'],
    learnLevel: 5,
    cost: 35,
    castTime: 0,
    cooldown: 12,
    range: 0,
    school: 'holy',
    projectile: false,
    requiresTarget: false,
    effects: [{ type: 'aoeDamage', min: 55, max: 70, radius: 6, softCap: 5 }],
    description:
      "Deal $d Holy damage to nearby enemies and generate 1 Devotion. Hitting at least one enemy reduces Final Edict's remaining cooldown by 2 sec. Ascension increases its damage and radius.",
  },
  {
    id: 'faithforged_guard',
    name: 'Faithforged Guard',
    class: 'paladin',
    specs: ['retribution'],
    learnLevel: 7,
    cost: 20,
    castTime: 0,
    cooldown: 75,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'absorb', amount: 140, duration: 8 }],
    description:
      'Surround yourself with a shield that absorbs $d damage for 8 sec. Ascension increases the shield by 50%.',
  },
  {
    id: 'hammer_of_wrath',
    name: 'Hammer of Wrath',
    class: 'paladin',
    specs: ['retribution'],
    learnLevel: 9,
    cost: 0,
    castTime: 0,
    cooldown: 6,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    executeThreshold: 0.2,
    effects: [{ type: 'directDamage', min: 150, max: 180 }],
    description:
      "Hurl a holy hammer for $d damage and generate 1 Devotion. Usable below 20% health, or during Divine Ascension or Avenging Wrath. Dawn's Wrath grants an additional cast against any target that ignores its current cooldown and deals 20% more damage. Ascension increases its damage by 30%.",
  },
  {
    id: 'avenging_wrath',
    name: 'Avenging Wrath',
    class: 'paladin',
    learnLevel: 11,
    cost: 0,
    castTime: 0,
    cooldown: 120,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    offGcd: true,
    effects: [
      { type: 'selfBuff', kind: 'buff_dmg_done', value: 0.2, duration: 15 },
      { type: 'selfBuff', kind: 'buff_healing_done', value: 0.2, duration: 15 },
      { type: 'grantDevotion', amount: 10 },
    ],
    description:
      'Unfurl physical wings of golden holy power, gaining 10 Devotion and doubling Devotion generated by your abilities for 15 sec. Also increases damage and healing done by 20%. Retribution: enables Hammer of Wrath against any target.',
  },
  {
    id: 'sun_gods_verdict',
    name: 'Verdict of the Sun God',
    class: 'paladin',
    specs: ['retribution'],
    learnLevel: 20,
    cost: 0,
    castTime: 0,
    cooldown: 60,
    range: 30,
    school: 'holy',
    projectile: false,
    requiresTarget: true,
    offGcd: true,
    effects: [
      {
        type: 'sunGodVerdict',
        duration: 30,
        charges: 3,
        singleTargetMin: 360,
        singleTargetMax: 420,
        areaMin: 150,
        areaMax: 180,
        areaRadius: 8,
        areaSoftCap: 5,
        stunDuration: 1.5,
      },
    ],
    description:
      'Judge an enemy beneath the Verdict of the Sun God for 30 sec. Final Edict and Dawnfall inscribe one charge on a successful hit. The ability that lands the third charge dictates the sentence: Final Edict unleashes devastating damage on the condemned; Dawnfall detonates the verdict, damaging and stunning nearby enemies for 1.5 sec.',
  },
  {
    id: 'valkyrs_calling',
    name: "Valkyr's Calling",
    class: 'paladin',
    specs: ['retribution'],
    learnLevel: 13,
    cost: 50,
    castTime: 0,
    cooldown: 180,
    range: 20,
    school: 'holy',
    projectile: false,
    requiresTarget: true,
    effects: [{ type: 'valkyrsCalling', min: 150, max: 180, radius: 8, softCap: 5 }],
    description:
      'Ascend into the air, becoming immune to damage as you fly toward the enemy. After 2 sec, descend upon the target area for $d Holy damage and generate 1 Devotion. Ascension increases the impact damage by 50% and consumes 1 charge.',
  },
];

const holy: AbilityDef[] = [
  {
    id: 'sacred_form',
    name: 'Sacred Form',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 2,
    cost: 30,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    offGcd: true,
    effects: [
      {
        type: 'selfBuff',
        kind: 'sacred_form',
        value: 0.1,
        value2: 0.05,
        value3: 0.5,
        duration: 0,
        permanent: true,
      },
    ],
    description:
      'Enter a sacred state until death, increasing healing by 10%, spell critical chance by 5%, and reducing threat generated by 50%. Holy only.',
  },
  {
    id: 'mercy_lance',
    name: 'Mercy Lance',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 4,
    cost: 20,
    castTime: 1.75,
    cooldown: 0,
    range: 30,
    school: 'holy',
    projectile: false,
    requiresTarget: true,
    targetType: 'enemy',
    effects: [{ type: 'directDamage', min: 80, max: 100 }],
    description:
      'Deal $d Holy damage to an enemy and generate 1 Devotion when it deals damage. During Ascension, it consumes 1 charge to guarantee a critical hit.',
  },
  {
    id: 'dawns_embrace',
    name: "Dawn's Embrace",
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 3,
    cost: 90,
    castTime: 2.5,
    cooldown: 0,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    effects: [{ type: 'heal', min: 260, max: 310 }],
    description:
      'Deliver a powerful heal and generate 1 Devotion. Radiant Resonance reduces its mana cost by 50% and cast time to 1.5 sec. Ascension makes it instant and increases its healing by 35%.',
  },
  {
    id: 'radiant_chorus',
    name: 'Radiant Chorus',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 5,
    cost: 60,
    castTime: 2,
    cooldown: 12,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'aoeHeal', min: 90, max: 110, radius: 30 }],
    description:
      "Heal nearby allies for $d and generate 1 Devotion. Effectively healing at least 2 allies grants Radiant Resonance: your next Mending Light is instant, or your next Dawn's Embrace costs 50% less mana and casts in 1.5 sec. Ascension increases Radiant Chorus healing and radius.",
  },
  {
    id: 'life_covenant',
    name: 'Life Covenant',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 7,
    cost: 40,
    castTime: 0,
    cooldown: 90,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    offGcd: true,
    effects: [{ type: 'buffTarget', kind: 'buff_dr', value: 0.4, duration: 6 }],
    description:
      "Reduce an ally's damage taken by 40% for 6 sec. During Ascension it also grants a 120-point shield without consuming a charge.",
  },
  {
    id: 'aegis_first_dawn',
    name: 'Aegis of the First Dawn',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 20,
    cost: 150,
    castTime: 0,
    cooldown: 180,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    channel: { duration: 5, ticks: 5 },
    effects: [
      {
        type: 'paladinAegis',
        radius: 10,
        tickMin: 35,
        tickMax: 45,
        finalMin: 120,
        finalMax: 150,
        damageReduction: 0.5,
        speedMult: 1.3,
        speedDuration: 4,
      },
    ],
    description:
      'Channel for 5 sec, creating a 10 meter holy dome. Allies inside are healed every second and take 50% less damage. Completing the channel releases a final heal and grants 30% movement speed for 4 sec.',
  },
];

const protection: AbilityDef[] = [
  {
    id: 'veilbound_march',
    name: 'Veilbound March',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 13,
    cost: 0,
    castTime: 0,
    cooldown: 75,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'veilboundMarch', duration: 4, speedMult: 1.4, armorPct: 30 }],
    description:
      'Become ethereal for 4 sec, gaining 40% movement speed and 30% armor and becoming immune to roots, slows, and displacement. Enemies you pass through are Veil Marked for 6 sec, taking Holy damage each second, dealing 20% less damage to you, and generating extra threat. The first mark grants 1 Devotion. When the march ends, nearby marked enemies take a final burst. Ascension increases the burst by 50% and lightly pulls them toward you.',
  },
  {
    id: 'vowkeeper_strike',
    name: 'Vowkeeper Strike',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 1,
    cost: 0,
    castTime: 0,
    cooldown: 5,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    threat: { mult: 3 },
    effects: [{ type: 'weaponStrike', bonus: 21, weaponMult: 1 }],
    description:
      'Strike with high threat and generate 1 Devotion. A successful strike has a 20% chance to grant Solar Reprisal for 8 sec; each successful block has a 25% chance. Solar Reprisal empowers your next Sunward Disc, Hammer of Grace, or Mending Light. Ascension also grants a small absorption shield.',
  },
  {
    id: 'bastion_rite',
    name: 'Bastion Rite',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 3,
    cost: 20,
    castTime: 0,
    cooldown: 10,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [
      { type: 'selfBuff', kind: 'buff_dr_phys', value: 0.2, duration: 6 },
      { type: 'selfBuff', kind: 'buff_block', value: 0.2, duration: 6 },
    ],
    description:
      'Reduce physical damage taken by 20% and increase block chance by 20% for 6 sec. Ascension extends the duration to 10 sec.',
  },
  {
    id: 'sunward_disc',
    name: 'Sunward Disc',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 5,
    cost: 25,
    castTime: 0,
    cooldown: 10,
    range: 30,
    school: 'holy',
    projectile: true,
    projectileFx: 'paladinSunwardDisc',
    requiresTarget: true,
    requiresShield: true,
    threat: { mult: 3 },
    effects: [
      { type: 'directDamage', min: 90, max: 110 },
      { type: 'chainDamage', min: 60, max: 75, jumps: 2, falloff: 1, radius: 10 },
    ],
    description:
      'Requires a shield. Hurl a radiant disc that strikes and then bounces between nearby enemies. Each damaging impact generates 1 Devotion. Solar Reprisal makes Sunward Disc cost no mana, ignore its cooldown, and deal 20% more damage. Ascension empowers 5 bounces.',
  },
  {
    id: 'sacred_challenge',
    name: 'Sacred Goad',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 6,
    cost: 0,
    castTime: 0,
    cooldown: 10,
    range: 30,
    school: 'holy',
    projectile: false,
    requiresTarget: true,
    offGcd: true,
    effects: [{ type: 'taunt' }],
    description:
      'Compel an enemy to attack you. During Ascension it also reduces all damage received by 15% for 4 sec without consuming a charge.',
  },
  {
    id: 'bastion_sweep',
    name: 'Bastion Sweep',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 7,
    cost: 0,
    castTime: 0,
    cooldown: 6,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    requiresShield: true,
    threat: { mult: 3.5 },
    effects: [
      {
        type: 'aoeDamage',
        min: 72,
        max: 88,
        radius: 6,
        frontal: true,
        frontalHalfAngle: Math.PI / 2,
        softCap: 5,
      },
    ],
    description:
      'Sweep your equipped shield through enemies in a 180 degree frontal arc for $d Holy damage with high threat and generate 1 Devotion. Ascension increases damage by 30% and radius to 8 m.',
  },
  {
    id: 'holy_shield',
    name: 'Hallowed Wall',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 7,
    cost: 0,
    castTime: 0,
    cooldown: 8,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    offGcd: true,
    effects: [
      { type: 'selfBuff', kind: 'buff_block', value: 0.3, duration: 8 },
      { type: 'absorb', amount: 90, duration: 8, auraId: 'holy_shield_absorb' },
      { type: 'threatPulse', amount: 150, radius: 8 },
    ],
    description:
      'Gain 30% block and an absorb shield for 8 sec, releasing a pulse of threat. Ascension strengthens and extends the defense.',
  },
  {
    id: 'oath_chain',
    name: 'Oath Chain',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 9,
    cost: 0,
    castTime: 0,
    cooldown: 18,
    range: 30,
    school: 'holy',
    projectile: false,
    requiresTarget: true,
    offGcd: true,
    effects: [
      {
        type: 'pullTarget',
        stopDistance: 3,
        travelSpeed: 18,
        slowMult: 0.5,
        slowDuration: 4,
      },
    ],
    description:
      'Instantly bind a distant enemy with a sacred chain. The enemy travels toward you at 18 m per second until it reaches 3 m, then is slowed by 50% for 4 sec. During Ascension it binds a second nearby enemy.',
  },
  {
    id: 'consecration',
    name: 'Holy Ground',
    class: 'paladin',
    specs: ['protection', 'retribution'],
    learnLevel: 10,
    cost: 35,
    castTime: 0,
    cooldown: 12,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    threat: { mult: 3 },
    effects: [
      {
        type: 'groundAoE',
        min: 22,
        max: 28,
        radius: 6,
        duration: 9,
        interval: 1,
        devotionOnFirstHit: 1,
      },
    ],
    description:
      'Consecrate the ground beneath you for 9 sec, dealing $d Holy damage with high threat every second. The first impact generates 1 Devotion. Protection Paladins take 5% less damage while standing inside. Ascension increases its damage.',
  },
];

const devotions: AbilityDef[] = [
  {
    id: 'radiant_devotion',
    name: 'Radiant Devotion',
    class: 'paladin',
    learnLevel: 8,
    cost: 35,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [
      { type: 'buffTarget', kind: 'buff_spellpower', value: 20, duration: 1800, party: true },
    ],
    description:
      'Increase the spell power of you and party members by 20 for 30 min. Replaces your own Dawn or Grace Devotion, but coexists with Devotions from other Paladins.',
  },
  {
    id: 'dawn_devotion',
    name: 'Dawn Devotion',
    class: 'paladin',
    learnLevel: 10,
    cost: 35,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'buffTarget', kind: 'buff_ap', value: 40, duration: 1800, party: true }],
    description:
      'Increase the attack power of you and party members by 40 for 30 min. Replaces your own Radiant or Grace Devotion, but coexists with Devotions from other Paladins and with Warrior shouts.',
  },
  {
    id: 'grace_devotion',
    name: 'Grace Devotion',
    class: 'paladin',
    learnLevel: 12,
    cost: 35,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [
      {
        type: 'buffTarget',
        kind: 'buff_mana_grace',
        value: 15,
        value2: 0.03,
        duration: 1800,
        party: true,
      },
    ],
    description:
      'You and party members restore 15 mana every 5 sec and pay 3% less mana for 30 min. Replaces your own Radiant or Dawn Devotion, but coexists with Devotions from other Paladins.',
  },
];

export const PALADIN_CORE_ABILITIES: Readonly<Record<string, AbilityDef>> = Object.fromEntries(
  [...common, ...devotions, ...retribution, ...holy, ...protection].map((ability) => [
    ability.id,
    ability,
  ]),
);
