import type { AbilityDef } from '../types';

const common: AbilityDef[] = [
  {
    id: 'divine_ascension',
    name: 'Divine Ascension',
    class: 'paladin',
    learnLevel: 1,
    cost: 0,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'divineAscension' }],
    description:
      'Consume 20 Devotion to gain 5 Ascension charges for up to 25 sec. Marked abilities consume one charge and gain an additional effect.',
  },
  {
    id: 'devotion_ward',
    name: 'Devotion Aura',
    class: 'paladin',
    learnLevel: 2,
    cost: 30,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    exclusiveGroup: 'paladin_devotion',
    effects: [
      {
        type: 'buffTarget',
        kind: 'buff_dr',
        value: 0.05,
        duration: 0,
        permanent: true,
        party: true,
      },
    ],
    description:
      'Reduce damage taken by you and party members by 5% until death or replacement. You can provide only one Devotion, but Devotions from different Paladins can coexist.',
  },
  {
    id: 'hammer_of_grace',
    name: 'Hammer of Grace',
    class: 'paladin',
    learnLevel: 4,
    cost: 0,
    castTime: 0,
    cooldown: 10,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'weaponStrike', bonus: 28, weaponMult: 1.1, restoreMana: 70 }],
    description:
      'Strike with your weapon and restore 70 mana on a successful hit. Shares a cooldown with Hammer of Light.',
  },
  {
    id: 'hammer_of_light',
    name: 'Hammer of Light',
    class: 'paladin',
    learnLevel: 6,
    cost: 20,
    castTime: 0,
    cooldown: 10,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'weaponStrike', bonus: 28, weaponMult: 1.1, selfHealDamageFrac: 0.5 }],
    description:
      'Strike with your weapon and heal yourself for 50% of damage dealt. Shares a cooldown with Hammer of Grace.',
  },
  {
    id: 'hushbrand',
    name: 'Hushbrand',
    class: 'paladin',
    learnLevel: 4,
    cost: 0,
    castTime: 0,
    cooldown: 15,
    range: 5,
    school: 'physical',
    requiresTarget: true,
    offGcd: true,
    effects: [{ type: 'interrupt', lockout: 4 }],
    description: 'Interrupts spellcasting and prevents spells from that school for 4 sec.',
  },
  {
    id: 'unbinding_blessing',
    name: 'Unbinding Blessing',
    class: 'paladin',
    learnLevel: 6,
    cost: 30,
    castTime: 0,
    cooldown: 25,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    effects: [{ type: 'cleanseMovement' }],
    description: 'Removes movement-slowing and rooting effects from a friendly target.',
  },
  {
    id: 'guardian_covenant',
    name: 'Guardian Covenant',
    class: 'paladin',
    learnLevel: 8,
    cost: 35,
    castTime: 0,
    cooldown: 45,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    offGcd: true,
    effects: [{ type: 'buffTarget', kind: 'buff_dr', value: 0.2, duration: 8 }],
    description: 'Protects an ally, reducing their damage taken by 20% for 8 sec.',
  },
  {
    id: 'solar_step',
    name: 'Solar Step',
    class: 'paladin',
    learnLevel: 10,
    cost: 20,
    castTime: 0,
    cooldown: 30,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_speed', value: 2.5, duration: 2 }],
    description:
      'Surge forward at high speed for 2 sec. You can steer, but the forward movement cannot be stopped early.',
  },
  {
    id: 'solar_invocation',
    name: 'Solar Invocation',
    class: 'paladin',
    learnLevel: 12,
    cost: 80,
    castTime: 2,
    cooldown: 90,
    range: 0,
    school: 'holy',
    projectile: false,
    requiresTarget: false,
    effects: [{ type: 'aoeHeal', min: 180, max: 220, radius: 40, playersOnly: true }],
    description: 'Call upon the Light to heal all allied players within 40 m for $d.',
  },
  {
    id: 'recall_the_fallen',
    name: 'Recall the Fallen',
    class: 'paladin',
    learnLevel: 12,
    cost: 60,
    castTime: 8,
    cooldown: 0,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    targetsDead: true,
    partyOnlyTarget: true,
    requiresOutOfCombat: true,
    effects: [{ type: 'resurrectAlly', hpFrac: 0.35 }],
    description: 'Returns a dead group member to life with 35% health and mana.',
  },
  {
    id: 'beacon_of_light',
    name: 'Beacon of Light',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 16,
    cost: 60,
    castTime: 0,
    cooldown: 0,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    partyOnlyTarget: true,
    effects: [{ type: 'beaconOfLight' }],
    description:
      'Mark one group member as your Beacon of Light. 75% of your effective healing on other group members within 60 m also heals the Beacon. Lasts until either of you dies.',
  },
];

const retribution: AbilityDef[] = [
  {
    id: 'oathstrike',
    name: 'Oathstrike',
    class: 'paladin',
    specs: ['retribution'],
    learnLevel: 1,
    cost: 0,
    castTime: 0,
    cooldown: 5,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'weaponStrike', bonus: 21, weaponMult: 1 }],
    description:
      'Strike for weapon damage plus $d and generate 1 Devotion. Ascension repeats the strike at 60% power.',
  },
  {
    id: 'final_edict',
    name: 'Final Edict',
    class: 'paladin',
    specs: ['retribution'],
    learnLevel: 3,
    cost: 25,
    castTime: 0,
    cooldown: 8,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'weaponStrike', bonus: 52, weaponMult: 1.4 }],
    description:
      'Deliver a crushing weapon strike and generate 2 Devotion. Ascension also releases a Holy explosion around you.',
  },
  {
    id: 'dawnfall',
    name: 'Dawnfall',
    class: 'paladin',
    specs: ['retribution'],
    learnLevel: 5,
    cost: 35,
    castTime: 0,
    cooldown: 12,
    range: 0,
    school: 'holy',
    projectile: false,
    requiresTarget: false,
    effects: [{ type: 'aoeDamage', min: 55, max: 70, radius: 6, softCap: 5 }],
    description:
      'Deal $d Holy damage to nearby enemies and generate 2 Devotion. Ascension increases its damage and radius.',
  },
  {
    id: 'faithforged_guard',
    name: 'Faithforged Guard',
    class: 'paladin',
    specs: ['retribution'],
    learnLevel: 7,
    cost: 20,
    castTime: 0,
    cooldown: 75,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'absorb', amount: 140, duration: 8 }],
    description:
      'Surround yourself with a shield that absorbs $d damage for 8 sec. Ascension increases the shield by 50%.',
  },
  {
    id: 'hammer_of_wrath',
    name: 'Hammer of Wrath',
    class: 'paladin',
    specs: ['retribution'],
    learnLevel: 9,
    cost: 0,
    castTime: 0,
    cooldown: 6,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    executeThreshold: 0.2,
    effects: [{ type: 'directDamage', min: 150, max: 180 }],
    description:
      'Hurl a holy hammer for $d damage and generate 1 Devotion. Usable below 20% health, or during Divine Ascension or Avenging Wrath. Ascension increases its damage by 30%.',
  },
  {
    id: 'avenging_wrath',
    name: 'Avenging Wrath',
    class: 'paladin',
    specs: ['retribution'],
    learnLevel: 11,
    cost: 0,
    castTime: 0,
    cooldown: 120,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'selfBuff', kind: 'buff_dmg_done', value: 0.2, duration: 15 }],
    description:
      'Unfurl wings of holy power, increasing all damage dealt by 20% for 15 sec and enabling Hammer of Wrath against any target.',
  },
];

const holy: AbilityDef[] = [
  {
    id: 'sacred_form',
    name: 'Sacred Form',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 2,
    cost: 30,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    offGcd: true,
    effects: [
      {
        type: 'selfBuff',
        kind: 'sacred_form',
        value: 0.1,
        value2: 0.05,
        value3: 0.5,
        duration: 0,
        permanent: true,
      },
    ],
    description:
      'Enter a sacred state until death, increasing healing by 10%, spell critical chance by 5%, and reducing threat generated by 50%. Holy only.',
  },
  {
    id: 'mercy_lance',
    name: 'Mercy Lance',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 1,
    cost: 20,
    castTime: 0,
    cooldown: 6,
    range: 30,
    school: 'holy',
    projectile: false,
    requiresTarget: true,
    targetType: 'any',
    effects: [
      { type: 'heal', min: 80, max: 100 },
      { type: 'directDamage', min: 80, max: 100 },
    ],
    description:
      'Heal an ally or damage an enemy for $d and generate 1 Devotion. Ascension also heals a nearby ally when used to heal.',
  },
  {
    id: 'dawns_embrace',
    name: "Dawn's Embrace",
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 3,
    cost: 45,
    castTime: 1.5,
    cooldown: 10,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    effects: [{ type: 'heal', min: 260, max: 310 }],
    description:
      'Deliver a powerful heal and generate 2 Devotion. Ascension makes the spell instant and increases its healing by 35%.',
  },
  {
    id: 'radiant_chorus',
    name: 'Radiant Chorus',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 5,
    cost: 60,
    castTime: 2,
    cooldown: 12,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'aoeHeal', min: 90, max: 110, radius: 30 }],
    description:
      'Heal nearby allies for $d and generate 2 Devotion. Ascension increases its healing and radius.',
  },
  {
    id: 'life_covenant',
    name: 'Life Covenant',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 7,
    cost: 40,
    castTime: 0,
    cooldown: 90,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    offGcd: true,
    effects: [{ type: 'buffTarget', kind: 'buff_dr', value: 0.4, duration: 6 }],
    description:
      "Reduce an ally's damage taken by 40% for 6 sec. During Ascension it also grants a 120-point shield without consuming a charge.",
  },
  {
    id: 'aegis_first_dawn',
    name: 'Aegis of the First Dawn',
    class: 'paladin',
    specs: ['holy'],
    learnLevel: 20,
    cost: 150,
    castTime: 0,
    cooldown: 180,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    channel: { duration: 5, ticks: 5 },
    effects: [
      {
        type: 'paladinAegis',
        radius: 10,
        tickMin: 35,
        tickMax: 45,
        finalMin: 120,
        finalMax: 150,
        damageReduction: 0.5,
        speedMult: 1.3,
        speedDuration: 4,
      },
    ],
    description:
      'Channel for 5 sec, creating a 10 meter holy dome. Allies inside are healed every second and take 50% less damage. Completing the channel releases a final heal and grants 30% movement speed for 4 sec.',
  },
];

const protection: AbilityDef[] = [
  {
    id: 'vowkeeper_strike',
    name: 'Vowkeeper Strike',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 1,
    cost: 0,
    castTime: 0,
    cooldown: 5,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    threat: { mult: 3 },
    effects: [{ type: 'weaponStrike', bonus: 21, weaponMult: 1 }],
    description:
      'Strike with high threat and generate 1 Devotion. Ascension also grants a small absorption shield.',
  },
  {
    id: 'bastion_rite',
    name: 'Bastion Rite',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 3,
    cost: 20,
    castTime: 0,
    cooldown: 10,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [
      { type: 'selfBuff', kind: 'buff_dr_phys', value: 0.2, duration: 6 },
      { type: 'selfBuff', kind: 'buff_block', value: 0.2, duration: 6 },
    ],
    description:
      'Reduce physical damage taken by 20% for 6 sec and generate 1 Devotion. Ascension extends the duration to 10 sec.',
  },
  {
    id: 'sunward_disc',
    name: 'Sunward Disc',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 5,
    cost: 25,
    castTime: 0,
    cooldown: 10,
    range: 30,
    school: 'holy',
    projectile: false,
    requiresTarget: true,
    threat: { mult: 3 },
    effects: [
      { type: 'directDamage', min: 90, max: 110 },
      { type: 'chainDamage', min: 60, max: 75, jumps: 2, falloff: 1, radius: 10 },
    ],
    description:
      'Hurl a radiant disc that strikes and bounces to 2 enemies, generating 2 Devotion. Ascension empowers 5 bounces.',
  },
  {
    id: 'sacred_challenge',
    name: 'Sacred Goad',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 6,
    cost: 0,
    castTime: 0,
    cooldown: 10,
    range: 30,
    school: 'holy',
    projectile: false,
    requiresTarget: true,
    offGcd: true,
    effects: [{ type: 'taunt' }],
    description:
      'Compel an enemy to attack you. During Ascension it also reduces all damage received by 15% for 4 sec without consuming a charge.',
  },
  {
    id: 'bastion_sweep',
    name: 'Bastion Sweep',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 7,
    cost: 0,
    castTime: 0,
    cooldown: 6,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    threat: { mult: 3.5 },
    effects: [{ type: 'aoeDamage', min: 72, max: 88, radius: 6, softCap: 5 }],
    description:
      'Sweep your shield through nearby enemies for $d Holy damage with high threat and generate 1 Devotion. Ascension increases damage by 30% and radius to 8 m.',
  },
  {
    id: 'holy_shield',
    name: 'Holy Shield',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 7,
    cost: 0,
    devotionCost: 3,
    castTime: 0,
    cooldown: 8,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    offGcd: true,
    effects: [
      { type: 'selfBuff', kind: 'buff_block', value: 0.3, duration: 8 },
      { type: 'absorb', amount: 90, duration: 8, auraId: 'holy_shield_absorb' },
      { type: 'threatPulse', amount: 150, radius: 8 },
    ],
    description:
      'Spend 3 Devotion to gain 30% block and an absorb shield for 8 sec, releasing a pulse of threat. Ascension strengthens and extends the defense.',
  },
  {
    id: 'oath_chain',
    name: 'Oath Chain',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 9,
    cost: 0,
    castTime: 0,
    cooldown: 18,
    range: 30,
    school: 'holy',
    projectile: false,
    requiresTarget: true,
    offGcd: true,
    effects: [{ type: 'pullTarget', stopDistance: 3, slowMult: 0.5, slowDuration: 4 }],
    description:
      'Bind a distant enemy with a sacred chain, pulling it to within 3 m and slowing it by 50% for 4 sec. This utility is not empowered by Ascension.',
  },
  {
    id: 'consecration',
    name: 'Consecration',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 10,
    cost: 35,
    castTime: 0,
    cooldown: 9,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    threat: { mult: 3 },
    effects: [
      {
        type: 'groundAoE',
        min: 22,
        max: 28,
        radius: 8,
        duration: 9,
        interval: 1,
        devotionOnFirstHit: 1,
      },
    ],
    description:
      'Consecrate the ground beneath you for 9 sec, dealing $d Holy damage with high threat every second. The first impact generates 1 Devotion. Ascension increases damage and radius.',
  },
  {
    id: 'citadel_of_faith',
    name: 'Citadel of Faith',
    class: 'paladin',
    specs: ['protection'],
    learnLevel: 8,
    cost: 0,
    castTime: 0,
    cooldown: 120,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'selfBuff', kind: 'buff_dr', value: 0.4, duration: 10 }],
    description: 'Reduce all damage taken by 40% for 10 sec.',
  },
];

const devotions: AbilityDef[] = [
  {
    id: 'radiant_devotion',
    name: 'Radiant Devotion',
    class: 'paladin',
    learnLevel: 8,
    cost: 35,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    exclusiveGroup: 'paladin_devotion',
    effects: [
      { type: 'buffTarget', kind: 'buff_spellpower', value: 20, duration: 1800, party: true },
    ],
    description: 'Increase the spell power of you and party members by 20 for 30 min.',
  },
  {
    id: 'dawn_devotion',
    name: 'Dawn Devotion',
    class: 'paladin',
    learnLevel: 10,
    cost: 35,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    exclusiveGroup: 'paladin_devotion',
    effects: [{ type: 'buffTarget', kind: 'buff_ap', value: 40, duration: 1800, party: true }],
    description:
      'Increase the attack power of you and party members by 40 for 30 min. This Devotion coexists with Warrior shouts.',
  },
  {
    id: 'grace_devotion',
    name: 'Grace Devotion',
    class: 'paladin',
    learnLevel: 12,
    cost: 35,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    exclusiveGroup: 'paladin_devotion',
    effects: [
      {
        type: 'buffTarget',
        kind: 'buff_mana_grace',
        value: 15,
        value2: 0.06,
        duration: 180,
        party: true,
      },
    ],
    description:
      'You and party members restore 15 mana every 5 sec and pay 6% less mana for 3 min.',
  },
];

export const PALADIN_CORE_ABILITIES: Readonly<Record<string, AbilityDef>> = Object.fromEntries(
  [...common, ...devotions, ...retribution, ...holy, ...protection].map((ability) => [
    ability.id,
    ability,
  ]),
);
