import type { AbilityDef } from '../types';

// Priest v0.28 spec signatures live together so their ownership and tuning can
// evolve without growing the shared class catalog. Their custom combat effects
// are wired by the spec modules in src/sim/combat/priest/.
export const PRIEST_ABILITIES: Record<string, AbilityDef> = {
  veilstep: {
    id: 'veilstep',
    name: 'Veilstep',
    class: 'priest',
    learnLevel: 5,
    cost: 30,
    castTime: 0,
    cooldown: 18,
    range: 0,
    school: 'shadow',
    requiresTarget: false,
    effects: [{ type: 'blinkForward', distance: 10 }],
    description: 'Steps through the veil in the direction you are facing.',
  },
  scouring_mercy: {
    id: 'scouring_mercy',
    name: 'Scouring Mercy',
    class: 'priest',
    learnLevel: 10,
    specs: ['discipline'],
    cost: 75,
    castTime: 0,
    cooldown: 8,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'any',
    effects: [
      { type: 'directDamage', min: 72, max: 84 },
      { type: 'heal', min: 130, max: 155 },
    ],
    description:
      'Scours an enemy with holy power or delivers immediate mercy to a friendly target. Doctrine signature.',
  },
  seraphic_vigil: {
    id: 'seraphic_vigil',
    name: 'Seraphic Vigil',
    class: 'priest',
    learnLevel: 10,
    specs: ['holy'],
    cost: 80,
    castTime: 0,
    cooldown: 20,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    effects: [{ type: 'buffTarget', kind: 'heal_echo', value: 180, duration: 30 }],
    description:
      'Places a watchful blessing on one ally, restoring them when they become unsafe. Benison signature.',
  },
  summon_tithefiend: {
    id: 'summon_tithefiend',
    name: 'Call Tithefiend',
    class: 'priest',
    learnLevel: 10,
    specs: ['shadow'],
    cost: 60,
    castTime: 0,
    cooldown: 30,
    range: 0,
    school: 'shadow',
    requiresTarget: false,
    effects: [],
    description:
      'Consumes Gloomtithe to call a temporary Tithefiend that hunts your Effigy. Vespers signature.',
  },
  martyrs_aegis: {
    id: 'martyrs_aegis',
    name: "Martyr's Aegis",
    class: 'priest',
    learnLevel: 17,
    cost: 80,
    castTime: 0,
    cooldown: 120,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    effects: [{ type: 'buffTarget', kind: 'shield_wall', value: 0.4, duration: 8 }],
    description: 'Reduces one ally incoming damage by 40% for 8 sec.',
  },
  choir_of_deliverance: {
    id: 'choir_of_deliverance',
    name: 'Choir of Deliverance',
    class: 'priest',
    learnLevel: 17,
    cost: 150,
    castTime: 0,
    channel: { duration: 6, ticks: 3 },
    cooldown: 180,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'aoeHeal', min: 90, max: 110, radius: 30 }],
    description: 'Channels for 6 sec, healing nearby party members every 2 sec.',
  },
};
