// The Stormbrass Foundry's loot (docs/design/dungeon-rework/stormbrass_foundry.md,
// section 8): every boss drops one guaranteed piece of a three-way archetype
// group (Heavy: warrior, paladin, shaman; Agile: rogue, hunter; Caster: mage,
// priest, warlock, druid) and a rare chase row; the Prime Draft keeps a bonus
// group of three rares beside its finale gold. Normal pieces sit at the boss's
// level plus the quality bump (Line-Master Tock 19: uncommon 20, rare 22; the
// rest 20: uncommon 21, rare 23), stats exactly on primaryStatBudget with the
// stamina baseline model (item_budget.ts). The heroic epics read source level
// 25 (item level 31) with the five-man heroic ratings, each matched to its
// same-slot shipped sibling in heroic_loot.ts. Rares in a boss's base table get
// their Heroic variant generated (content/heroic_variants.ts), never authored
// here. The two trinkets live with the others in content/trinkets.ts; the
// Draft Record is the quest object of The First Draft.
//
// Names were re-checked at authoring (2026-10-01, design section 10): every
// item name is a generic English compound; "Stormbrass" is clear for games.

import type { ItemDef } from '../types';
import { ARMOR_RATING, FIVE_MAN_WEAPON_RATING } from './heroic_loot';

const HEAVY = ['warrior', 'paladin', 'shaman'] as ItemDef['requiredClass'];
const AGILE = ['rogue', 'hunter'] as ItemDef['requiredClass'];
const CASTER = ['mage', 'priest', 'warlock', 'druid'] as ItemDef['requiredClass'];
const HUNTER_ONLY = ['hunter'] as ItemDef['requiredClass'];
const CASTER_WEAPON_CLASSES = [
  'mage',
  'priest',
  'warlock',
  'druid',
  'shaman',
] as ItemDef['requiredClass'];

export const STORMBRASS_FOUNDRY_ITEMS: Record<string, ItemDef> = {
  // ---- Line-Master Ambrel Tock (level 19) ----
  riveters_gauntlets: {
    id: 'riveters_gauntlets',
    name: "Riveter's Gauntlets",
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'uncommon',
    stats: { armor: 104, str: 3, sta: 2 },
    sellValue: 850,
    requiredClass: HEAVY,
  },
  beltrunners_boots: {
    id: 'beltrunners_boots',
    name: "Beltrunner's Boots",
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 70, agi: 3, sta: 2 },
    sellValue: 850,
    requiredClass: AGILE,
  },
  draftsmans_mantle: {
    id: 'draftsmans_mantle',
    name: "Draftsman's Mantle",
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'uncommon',
    stats: { armor: 44, int: 4, spi: 2, sta: 2 },
    sellValue: 850,
    requiredClass: CASTER,
  },
  tocks_torque_wrench: {
    id: 'tocks_torque_wrench',
    name: "Tock's Torque Wrench",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 28, max: 41, speed: 2.6 },
    stats: { str: 7, sta: 5 },
    sellValue: 2400,
    requiredClass: HEAVY,
  },
  // ---- The Rangewarden (level 20) ----
  proofplate_legguards: {
    id: 'proofplate_legguards',
    name: 'Proofplate Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'uncommon',
    stats: { armor: 153, str: 4, sta: 3 },
    sellValue: 900,
    requiredClass: HEAVY,
  },
  rangefinders_hood: {
    id: 'rangefinders_hood',
    name: "Rangefinder's Hood",
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'uncommon',
    stats: { armor: 86, agi: 4, sta: 3 },
    sellValue: 900,
    requiredClass: AGILE,
  },
  coilwound_cord: {
    id: 'coilwound_cord',
    name: 'Coilwound Cord',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'waist',
    quality: 'uncommon',
    stats: { armor: 34, int: 4, spi: 2, sta: 2 },
    sellValue: 850,
    requiredClass: CASTER,
  },
  proving_range_quiver: {
    id: 'proving_range_quiver',
    name: 'Proving-Range Quiver',
    kind: 'held_offhand',
    slot: 'offhand',
    quality: 'rare',
    // The Rangewarden (level 20) -> item level 23 on the worn-offhand budget,
    // primaryStatBudget(23, rare, offhand, WORN_OFFHAND_STAT_MULT) = 6, the
    // Gravewyrm Bone Quiver's rung.
    occupiesHand: false,
    stats: { agi: 4, sta: 2 },
    sellValue: 900,
    requiredClass: HUNTER_ONLY,
  },
  // ---- The Voltaic Warden (level 20) ----
  grounding_pauldrons: {
    id: 'grounding_pauldrons',
    name: 'Grounding Pauldrons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'uncommon',
    stats: { armor: 128, str: 4, sta: 2 },
    sellValue: 900,
    requiredClass: HEAVY,
  },
  arcstep_treads: {
    id: 'arcstep_treads',
    name: 'Arcstep Treads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 72, agi: 3, sta: 2 },
    sellValue: 900,
    requiredClass: AGILE,
  },
  stormglass_circlet: {
    id: 'stormglass_circlet',
    name: 'Stormglass Circlet',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'uncommon',
    stats: { armor: 49, int: 4, spi: 3, sta: 2 },
    sellValue: 900,
    requiredClass: CASTER,
  },
  voltaic_coil_staff: {
    id: 'voltaic_coil_staff',
    name: 'Voltaic Coil-Staff',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'rare',
    weapon: { min: 37, max: 57, speed: 3.0 },
    stats: { int: 11, spi: 6, sta: 6 },
    sellValue: 3200,
    requiredClass: CASTER_WEAPON_CLASSES,
  },
  // ---- The Prime Draft (level 20) ----
  draftplate_breastplate: {
    id: 'draftplate_breastplate',
    name: 'Draftplate Breastplate',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 170, str: 5, sta: 3 },
    sellValue: 900,
    requiredClass: HEAVY,
  },
  gearwork_jerkin: {
    id: 'gearwork_jerkin',
    name: 'Gearwork Jerkin',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 105, agi: 5, sta: 3 },
    sellValue: 900,
    requiredClass: AGILE,
  },
  stormbrass_robe: {
    id: 'stormbrass_robe',
    name: 'Stormbrass Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'uncommon',
    stats: { armor: 60, int: 5, spi: 3, sta: 3 },
    sellValue: 900,
    requiredClass: CASTER,
  },
  piston_maul: {
    id: 'piston_maul',
    name: "Prime Draft's Piston Maul",
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'rare',
    weapon: { min: 43, max: 63, speed: 3.4 },
    stats: { str: 11, sta: 6 },
    sellValue: 3200,
    requiredClass: HEAVY,
  },
  cellspark_dagger: {
    id: 'cellspark_dagger',
    name: 'Cellspark Dagger',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 19, max: 30, speed: 1.8, dagger: true },
    stats: { agi: 9, sta: 4 },
    sellValue: 3000,
    requiredClass: AGILE,
  },
  governors_scepter: {
    id: 'governors_scepter',
    name: "Governor's Scepter",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 26, max: 39, speed: 2.4 },
    stats: { int: 9, spi: 4, sta: 4 },
    sellValue: 3000,
    requiredClass: CASTER_WEAPON_CLASSES,
  },
  // ---- Heroic epics (source level 25, item level 31) ----
  line_masters_steam_hammer: {
    id: 'line_masters_steam_hammer',
    name: "Line-Master's Steam Hammer",
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    requiredLevel: 20,
    // The Greatfang of the Basin's line: a five-man heroic HEAVY two-hander.
    weapon: { min: 50, max: 75, speed: 3.4 },
    stats: { str: 17, sta: 12 },
    hitRating: FIVE_MAN_WEAPON_RATING,
    sellValue: 15000,
    requiredClass: HEAVY,
  },
  rangewardens_targeting_visor: {
    id: 'rangewardens_targeting_visor',
    name: "Rangewarden's Targeting Visor",
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 168, agi: 10, sta: 8 },
    hitRating: ARMOR_RATING,
    sellValue: 12000,
    requiredClass: AGILE,
  },
  stormglass_robes: {
    id: 'stormglass_robes',
    name: 'Stormglass Robes',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 90, int: 12, spi: 10, sta: 7 },
    hasteRating: ARMOR_RATING,
    sellValue: 14000,
    requiredClass: CASTER,
  },
  prime_draft_core_plate: {
    id: 'prime_draft_core_plate',
    name: 'Prime Draft Core-Plate',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 335, str: 12, sta: 10 },
    critRating: ARMOR_RATING,
    sellValue: 14000,
    requiredClass: HEAVY,
  },
  heartless_gearmask: {
    id: 'heartless_gearmask',
    name: 'Heartless Gearmask',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 76, int: 11, spi: 7, sta: 6 },
    hasteRating: ARMOR_RATING,
    sellValue: 12000,
    requiredClass: CASTER,
  },
  // ---- The First Draft's quest object (the Prime Draft's opened chest) ----
  draft_record: {
    id: 'draft_record',
    name: 'Draft Record',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_sf_first_draft',
    noVendorSell: true,
  },
};
